import { Link, useParams } from 'react-router-dom';
const pages={
 privacy:{title:'Privacy information',paragraphs:['We use account details, saved addresses and order information to operate your account and fulfil purchases. Wishlists are stored with your account.','Online payments are handled by Razorpay. Product images use Cloudinary. Email services handle account recovery and order messages. The product assistant may send your question to Groq and Jina; do not enter personal, payment or medical records into chat.','Guest carts and cached profile information use browser storage. Authentication uses cookies. Contact us with questions about your information or to request account-data assistance.']},
 terms:{title:'Shopping information',paragraphs:['Review the product details, package label, delivery address and final checkout total before placing an order. Product listings provide general information and are not medical advice.','An online order is confirmed only after payment verification. If the payment window closes, you can resume payment from Your orders. If you were charged but confirmation is missing, check Your orders and contact support before paying again.','Stock and pricing are checked on the server at checkout. Contact us if you need clarification about a product before ordering.']},
 shipping:{title:'Shipping information',paragraphs:['Delivery costs ₹49 for a product subtotal of ₹999 or less. Delivery is free above ₹999. Cash on delivery adds ₹29. The checkout displays your final total.','Track order shows the status recorded by our store. It is not a live courier map. Contact us to confirm delivery availability and timing for your location.']},
 refunds:{title:'Cancellations, returns and refunds',paragraphs:['You can request cancellation from Your orders before shipment. If an online payment is still processing, retry shortly. A successfully cancelled order restores reserved stock.','For a delivered order, submit a return reason from Your orders. This records a request for support review; it does not automatically approve a return or issue a refund.','Online refund requests are sent to Razorpay. A pending refund remains pending until processing is confirmed. Cash-on-delivery refunds require an offline settlement arranged with support. Refund timing depends on the payment provider and bank.']},
 faq:{title:'Frequently asked questions',paragraphs:['How do I recover my account? Use Forgot password on the sign-in page. Reset links expire in 30 minutes and can be used once.','Where are my saved products? Your wishlist is linked to your account and available after signing in on another device.','What can Vaidya answer? Catalog questions and reviewed general information about Ayurveda, herbs, nuts and dried fruits. It does not diagnose, prescribe, suggest doses or provide harmful instructions.','How can I get help? Use the contact form and include your order number if applicable.']},
};
export default function InformationPage(){const {page}=useParams();const content=pages[page];return <section className="max-w-3xl mx-auto px-6 py-16"><h1 className="text-3xl font-serif mb-8">{content?.title||'Page not found'}</h1><div className="space-y-5 leading-relaxed">{content?.paragraphs.map(text=><p key={text}>{text}</p>)}</div><Link className="inline-block underline mt-8" to="/contact">Contact Anjaneya Herbals</Link></section>;}
