ALTER TABLE orders ADD COLUMN IF NOT EXISTS gateway_order_id VARCHAR(255);
CREATE UNIQUE INDEX IF NOT EXISTS orders_gateway_order_unique ON orders(gateway_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS orders_payment_unique ON orders(payment_id) WHERE payment_id IS NOT NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cod_charges NUMERIC(10,2) DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS return_reason VARCHAR(1000);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS return_requested_at TIMESTAMP;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS stock_restored BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS wishlist_items (user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE, PRIMARY KEY(user_id, product_id));
CREATE TABLE IF NOT EXISTS password_reset_tokens (token_hash VARCHAR(64) PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS newsletter_subscriptions (email VARCHAR(254) PRIMARY KEY, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 0;
